# Generated by Django 2.0.4 on 2018-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('goods_id', models.CharField(max_length=100)),
                ('comment_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='netbook',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('goods_id', models.CharField(max_length=100)),
                ('comment_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('goods_id', models.CharField(max_length=100)),
                ('comment_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('datatime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
